version: "3"
services:
  nginx:
    restart: always
    image: nginx:1.11.6-alpine
    ports:
      - 80:80
      # - 443:443
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/log:/var/log/nginx
      - ./docker/nginx/www:/var/www
      - ./docker/transmission/download:/download
  node:
    build: ./docker/node
    volumes:
      - ./docker/node/app:/app
      - /app/node_modules
    ports:
     - "3000:3000/tcp"
    depends_on:
      - mongo
  mongo:
    restart: on-failure
    image:  mongo:3.4
    volumes:
      - ./docker/mongo/db:/data/db:rw
    ports:
      - "28017:27017/tcp"
    command: --maxConns 4096
    sysctls:
      net.core.somaxconn: 16240
  transmission:
    restart: always
    image: "dperson/transmission"
    container_name: transmission
    ports:
      - "9091:9091/tcp"
    volumes:
      - ./docker/transmission/download:/var/lib/transmission-daemon/Downloads
      - ./docker/transmission/incomplete:/var/lib/transmission-daemon/incomplete
      - ./docker/transmission/info:/var/lib/transmission-daemon/info
      - ./docker/transmission/.config:/etc/transmission-daemon