version: "3"
services:
  node:
    build: ./docker/node
    volumes:
      - ./docker/node/app:/app
    ports:
     - "3000:3000/tcp"
  mongo:
    restart: on-failure
    image:  mongo:3.4
    volumes:
      - ./docker/mongo/db:/data/db:rw
    ports:
      - "28017:27017/tcp"
    command: --maxConns 4096
    sysctls:
      net.core.somaxconn: 16240